import 'game_definition.dart';

abstract final class GameCatalog {
  static const games = <GameDefinition>[
    GameDefinition(
      id: 'chrono-lock',
      title: 'قفل زمان',
      shortDescription: 'تایمر پنهان را دقیقاً در زمان هدف متوقف کن.',
      description: 'در شروع هر دور یک زمان هدف نمایش داده می‌شود. بعد از شروع، تایمر ناپدید می‌شود و باید فقط با حس زمان‌بندی خودت دکمهٔ توقف را بزنی. هرچه خطا کمتر باشد، امتیاز بیشتر است.',
      instructions: [
        'زمان هدف را به خاطر بسپار.',
        'شروع را بزن؛ تایمر پنهان می‌شود.',
        'در لحظهٔ مناسب توقف کن.',
        'امتیاز بر اساس فاصله از زمان هدف محاسبه می‌شود.',
      ],
      imageAsset: 'assets/game_art/chrono_lock.png',
      minimumPlayers: 1,
      maximumPlayers: 8,
      playKind: GamePlayKind.local,
      difficulty: GameDifficulty.easy,
      tags: ['زمان‌بندی', 'تمرکز', 'رقابتی'],
      playRoute: '/games/chrono-lock',
    ),
    GameDefinition(
      id: 'hidden-fuse',
      title: 'فیوز پنهان',
      shortDescription: 'دکمه را نگه دار، امتیاز جمع کن و پیش از انفجار رها کن.',
      description: 'مدت فیوز در هر دور به‌صورت قطعی اما مخفی تعیین می‌شود. با نگه‌داشتن دکمه امتیاز سریع‌تر زیاد می‌شود؛ اگر دیر رها کنی تمام امتیاز دور از بین می‌رود.',
      instructions: [
        'دکمهٔ بزرگ را لمس و نگه دار.',
        'هرچه بیشتر نگه داری امتیاز بیشتری می‌گیری.',
        'پیش از انفجار انگشتت را بردار.',
        'انفجار، امتیاز همان دور را صفر می‌کند.',
      ],
      imageAsset: 'assets/game_art/hidden_fuse.png',
      minimumPlayers: 1,
      maximumPlayers: 8,
      playKind: GamePlayKind.local,
      difficulty: GameDifficulty.medium,
      tags: ['ریسک', 'واکنش', 'هیجان'],
      playRoute: '/games/hidden-fuse',
    ),
    GameDefinition(
      id: 'ghost-trace',
      title: 'رد شبح',
      shortDescription: 'مسیر محوشده را با دقت دوباره رسم کن.',
      description: 'یک مسیر کوتاه چند ثانیه دیده می‌شود و سپس ناپدید می‌شود. مسیر را از حافظه بازسازی کن؛ شکل، طول، جهت و نقطهٔ پایان همگی در امتیاز اثر دارند.',
      instructions: [
        'مسیر روشن را با دقت نگاه کن.',
        'پس از محوشدن، روی صفحه مسیر را رسم کن.',
        'دکمهٔ محاسبه را بزن.',
        'برای دور جدید مسیر تازه تولید کن.',
      ],
      imageAsset: 'assets/game_art/ghost_trace.png',
      minimumPlayers: 1,
      maximumPlayers: 8,
      playKind: GamePlayKind.local,
      difficulty: GameDifficulty.medium,
      tags: ['حافظه', 'دقت', 'نقاشی'],
      playRoute: '/games/ghost-trace',
    ),
    GameDefinition(
      id: 'word-forge',
      title: 'واژه‌ساز',
      shortDescription: 'با حروف محدود، واژه‌های معتبر و پرامتیاز بساز.',
      description: 'هر دور مجموعه‌ای محدود از حروف در اختیار داری. کلمات فارسی به‌صورت آفلاین بررسی و نرمال‌سازی می‌شوند. واژهٔ تکراری امتیاز دوباره نمی‌گیرد.',
      instructions: [
        'حروف موجود را بررسی کن.',
        'یک واژهٔ فارسی وارد کن.',
        'واژه باید فقط از حروف موجود ساخته شود.',
        'حروف کمیاب و واژه‌های بلند امتیاز بیشتری دارند.',
      ],
      imageAsset: 'assets/game_art/word_forge.png',
      minimumPlayers: 1,
      maximumPlayers: 8,
      playKind: GamePlayKind.local,
      difficulty: GameDifficulty.medium,
      tags: ['واژه', 'فارسی', 'فکری'],
      playRoute: '/games/word-forge',
    ),
    GameDefinition(
      id: 'memory-grid',
      title: 'شبکهٔ حافظه',
      shortDescription: 'خانه‌های روشن را به خاطر بسپار و همان الگو را تکرار کن.',
      description: 'چند خانه برای مدت کوتاه روشن می‌شوند. بعد از خاموش‌شدن باید دقیقاً همان خانه‌ها را انتخاب کنی. با هر دور، شبکه سخت‌تر می‌شود.',
      instructions: [
        'الگوی خانه‌های روشن را به خاطر بسپار.',
        'بعد از خاموش‌شدن، همان خانه‌ها را انتخاب کن.',
        'ثبت پاسخ را بزن.',
        'هر پاسخ کامل، مرحله را سخت‌تر می‌کند.',
      ],
      imageAsset: 'assets/game_art/memory_grid.png',
      minimumPlayers: 1,
      maximumPlayers: 8,
      playKind: GamePlayKind.local,
      difficulty: GameDifficulty.easy,
      tags: ['حافظه', 'الگو', 'سریع'],
      playRoute: '/games/memory-grid',
      isNew: true,
    ),
    GameDefinition(
      id: 'color-clash',
      title: 'نبرد رنگ‌ها',
      shortDescription: 'رنگ واقعی نوشته را انتخاب کن، نه معنای آن را.',
      description: 'نام یک رنگ با رنگی متفاوت نمایش داده می‌شود. باید رنگ ظاهری نوشته را سریع انتخاب کنی و در دام معنای کلمه نیفتی.',
      instructions: [
        'به رنگ ظاهری کلمه نگاه کن.',
        'معنای نوشته را نادیده بگیر.',
        'رنگ درست را از دکمه‌ها انتخاب کن.',
        'پاسخ سریع‌تر امتیاز بیشتری دارد.',
      ],
      imageAsset: 'assets/game_art/color_clash.png',
      minimumPlayers: 1,
      maximumPlayers: 8,
      playKind: GamePlayKind.local,
      difficulty: GameDifficulty.medium,
      tags: ['واکنش', 'رنگ', 'تمرکز'],
      playRoute: '/games/color-clash',
      isNew: true,
    ),
    GameDefinition(
      id: 'number-rush',
      title: 'یورش عددی',
      shortDescription: 'هدف عددی را با انتخاب سریع گزینه‌های درست بساز.',
      description: 'یک هدف و چند عدد تصادفی نمایش داده می‌شود. دو عددی را انتخاب کن که جمع آن‌ها برابر هدف باشد. پاسخ‌های درست پیاپی امتیاز ترکیبی می‌سازند.',
      instructions: [
        'عدد هدف را ببین.',
        'دو عدد را انتخاب کن.',
        'مجموع آن‌ها باید برابر هدف باشد.',
        'پاسخ درست، دور بعدی و امتیاز بیشتر می‌آورد.',
      ],
      imageAsset: 'assets/game_art/number_rush.png',
      minimumPlayers: 1,
      maximumPlayers: 8,
      playKind: GamePlayKind.local,
      difficulty: GameDifficulty.easy,
      tags: ['عدد', 'سرعت', 'محاسبه'],
      playRoute: '/games/number-rush',
      isNew: true,
    ),
    GameDefinition(
      id: 'tap-storm',
      title: 'طوفان ضربه',
      shortDescription: 'در زمان محدود بیشترین ضربهٔ معتبر را ثبت کن.',
      description: 'یک رقابت کوتاه و پرسرعت است. تنها لمس‌های داخل ناحیهٔ فعال شمرده می‌شوند و شمارنده بر پایهٔ زمان monotonic اجرا می‌شود.',
      instructions: [
        'شروع را بزن.',
        'در مدت پنج ثانیه روی هدف ضربه بزن.',
        'فقط ضربه‌های داخل هدف ثبت می‌شوند.',
        'پس از پایان، نرخ ضربه و امتیاز نمایش داده می‌شود.',
      ],
      imageAsset: 'assets/game_art/tap_storm.png',
      minimumPlayers: 1,
      maximumPlayers: 8,
      playKind: GamePlayKind.local,
      difficulty: GameDifficulty.easy,
      tags: ['سرعت', 'لمس', 'رکورد'],
      playRoute: '/games/tap-storm',
      isNew: true,
    ),
    GameDefinition(
      id: 'signal-snap',
      title: 'شکار سیگنال',
      shortDescription: 'پس از علامت میزبان، سریع‌تر از همه واکنش نشان بده.',
      description: 'بازی ویژهٔ LAN است. میزبان زمان شروع را اعلام می‌کند و هر لمس با Clock Sync به زمان میزبان تبدیل می‌شود. لمس زودهنگام خطا است و نتیجه را Host تعیین می‌کند.',
      instructions: [
        'یک دستگاه اتاق LAN بسازد.',
        'بازیکنان به اتاق متصل شوند.',
        'تا نمایش علامت صبر کنید.',
        'اولین لمس معتبر برنده است.',
      ],
      imageAsset: 'assets/game_art/signal_snap.png',
      minimumPlayers: 2,
      maximumPlayers: 8,
      playKind: GamePlayKind.lan,
      difficulty: GameDifficulty.easy,
      tags: ['LAN', 'واکنش', 'هم‌زمان'],
      playRoute: '/multiplayer',
    ),
    GameDefinition(
      id: 'shadow-path',
      title: 'مسیر سایه',
      shortDescription: 'حرکت‌های آینده را برنامه‌ریزی کن و هم‌زمان اجرا شو.',
      description: 'بازیکنان چند فرمان آینده را مخفیانه انتخاب می‌کنند. میزبان همهٔ فرمان‌ها را Tick به Tick هم‌زمان اجرا می‌کند؛ برخورد، تله و رسیدن به هدف قطعی هستند.',
      instructions: [
        'به اتاق LAN وارد شوید.',
        'چند حرکت آینده را انتخاب کنید.',
        'پس از قفل‌شدن، فرمان‌ها هم‌زمان اجرا می‌شوند.',
        'از دیوار، تله و برخورد با بازیکنان دوری کنید.',
      ],
      imageAsset: 'assets/game_art/shadow_path.png',
      minimumPlayers: 2,
      maximumPlayers: 8,
      playKind: GamePlayKind.lan,
      difficulty: GameDifficulty.hard,
      tags: ['LAN', 'استراتژی', 'هم‌زمان'],
      playRoute: '/multiplayer',
    ),
    GameDefinition(
      id: 'sketch-imposter',
      title: 'نقاش مرموز',
      shortDescription: 'نقاشی کن، رأی بده و بازیکن متفاوت را پیدا کن.',
      description: 'موضوع اصلی به بیشتر بازیکنان و موضوعی مشابه به یک Imposter داده می‌شود. همه داخل اپ نقاشی می‌کنند، آثار ناشناس نمایش داده می‌شوند و رأی‌گیری انجام می‌شود.',
      instructions: [
        'نقش خصوصی خودت را ببین.',
        'موضوع را بدون نوشتن کلمه نقاشی کن.',
        'نقاشی‌های ناشناس را بررسی کن.',
        'به بازیکن مشکوک رأی بده.',
      ],
      imageAsset: 'assets/game_art/sketch_imposter.png',
      minimumPlayers: 3,
      maximumPlayers: 8,
      playKind: GamePlayKind.lan,
      difficulty: GameDifficulty.medium,
      tags: ['LAN', 'نقاشی', 'استنتاج'],
      playRoute: '/multiplayer',
    ),
    GameDefinition(
      id: 'split-control',
      title: 'کنترل تقسیم‌شده',
      shortDescription: 'هر بازیکن فقط بخشی از کنترل یک وسیله را در دست دارد.',
      description: 'یک شبیه‌سازی همکاری LAN که در آن بازیکنان نقش‌های افقی، عمودی، توانایی و ترمز را جداگانه کنترل می‌کنند. هماهنگی تیمی برای رسیدن به هدف ضروری است.',
      instructions: [
        'اتاق LAN بسازید و نقش‌ها را تقسیم کنید.',
        'هر بازیکن فقط کنترل خودش را می‌بیند.',
        'با هم ارتباط برقرار کنید.',
        'با کمترین برخورد به هدف برسید.',
      ],
      imageAsset: 'assets/game_art/split_control.png',
      minimumPlayers: 2,
      maximumPlayers: 4,
      playKind: GamePlayKind.lan,
      difficulty: GameDifficulty.hard,
      tags: ['LAN', 'همکاری', 'کنترل'],
      playRoute: '/multiplayer',
    ),
  ];

  static GameDefinition? find(String id) {
    for (final game in games) {
      if (game.id == id) return game;
    }
    return null;
  }
}
